services:
  co-school:
    image: salmaba/doowaste:latest
    ports:
      - "9091:9091"
    depends_on:
      - co-school-db
    networks:
      - co-school-network
    deploy:
      restart_policy:
        condition: on-failure


  co-school-db:
    image: "mysql:latest"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=co_school
    ports:
      - "3306:3306"
    networks:
      - co-school-network
    volumes:
      - mysql-data:/var/lib/mysql


networks:
  co-school-network:
    driver: bridge
volumes:
  mysql-data: